In [7]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(["data/file1.csv", "data/file1.csv"])

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[1], [1], [1], [1]]
col1, col2, col3, col4 = tf.decode_csv(
    value, record_defaults=record_defaults)
features = tf.stack([col1, col2, col3])
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

with tf.Session() as sess:
  # Start populating the filename queue.
  coord = tf.train.Coordinator()
  threads = tf.train.start_queue_runners(coord=coord)

  for i in range(1200):
    # Retrieve a single instance:
    example, label = sess.run([features, col4])
    print(example, label)
    print(label)

  coord.request_stop()
  coord.join(threads)

[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1


[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1
[1 0 0] 0
[1 0 1] 0
[1 1 0] 1
[0 1 1] 1
[0 1 0] 0
[1 0 1] 1
[0 0 1] 1


In [3]:
print(features)

Tensor("stack:0", shape=(3,), dtype=int32)
